### ISSUE TITLE
Questions about aggregating global and local models

### ISSUE THREAD

**Issue by Zziwei** [jin530/LOCA#1]
Hi,

I am confused about how to aggregate global and local models. In the paper, there is a hyper-parameter alpha to weighted average outputs from global and local models. However, in the code, I did not find the place you use this weighted average method. Instead, it seems that you choose to use the output from the global model only when one user belongs to no local model. Like line 150 to 153 in LOCA_VAE.py. Am I understanding your code correctly?

BTW, thank you for the nice code and paper!

**Comment by jin530** [comment]
It's an excellent question!

Yes, the users who belong to no local model are covered by the global model.
In the paper, the last part of 3.2 explains it.
(https://arxiv.org/pdf/2103.16103.pdf)

![image](https://user-images.githubusercontent.com/35443268/118437315-5d2b8580-b71d-11eb-8cfe-50eae748c817.png)

**Comment by Zziwei** [comment]
Thank you!
