### ISSUE TITLE
Update the preprocessed datasets link

### ISSUE THREAD

**Issue by JP-25** [jin530/LOCA#3]
Can you update the preprocessed datasets link so we can download the .rating datasets? Thank you so much.

**Comment by jin530** [comment]
Hello, 

I uploaded the datasets on Github.
(https://github.com/jin530/LOCA/tree/main/data/recsys_data) 

Please let me know if there is any problem.
Thanks!

**Comment by JP-25** [comment]
Thank you so much, very nice code and really helpful
